INSERT INTO MOVIE_MEMBER VALUES(1,'Hugh','Jackman');
INSERT INTO MOVIE_MEMBER VALUES(2,'Steven','Spielberg');
INSERT INTO MOVIE_MEMBER VALUES(3,'Jon','Favreau');
INSERT INTO MOVIE_MEMBER VALUES(4,'George','Miller');
INSERT INTO MOVIE_MEMBER VALUES(5,'Tom','Hardy');

INSERT INTO DIRECTOR VALUES(2,'Steven','Spielberg');
INSERT INTO DIRECTOR VALUES(3,'Jon','Favreau');
INSERT INTO DIRECTOR VALUES(4,'George','Miller');

INSERT INTO MOVIE VALUES(1,'PG',5,4,2);
INSERT INTO MOVIE VALUES(2,'PG',8,7,3);
INSERT INTO MOVIE VALUES(3,'R18',7,8,4);

INSERT INTO TITLE VALUES('X-Men',1);
INSERT INTO TITLE VALUES('Iron Man',2);
INSERT INTO TITLE VALUES('Mad Max:Fury Road',3);

INSERT INTO GENRE VALUES(1,'Action');

INSERT INTO BELONGS_TO VALUES(1,1);
INSERT INTO BELONGS_TO VALUES(2,1);
INSERT INTO BELONGS_TO VALUES(3,1);

INSERT INTO CUSTOMER VALUES ('dave@gmail.com','Dave','Smith','123',NULL,1234,'Fake Street',NULL,'Toronto','M5T2L4',TO_DATE('1998/05/03 21:02:44', 'yyyy/mm/dd hh24:mi:ss'));
INSERT INTO CUSTOMER VALUES ('sam@gmail.com','Sam','Smith','abc',NULL,100,'Some Street',NULL,'Toronto','M1G8W3',TO_DATE('1997/03/01 21:02:44', 'yyyy/mm/dd hh24:mi:ss'));

INSERT INTO PURCHASES_OR_RENT VALUES('dave@gmail.com',1);

INSERT INTO REVIEW VALUES(4.5,'dave@gmail.com','Good movie.',1);
INSERT INTO REVIEW VALUES(8,'sam@gmail.com','Great movie.',2);

INSERT INTO ACTOR VALUES(1,'Hugh','Jackman');
INSERT INTO ACTOR VALUES(5,'Tom','Hardy');

INSERT INTO STARS VALUES(1,1);
INSERT INTO STARS VALUES(3,5);
